### PR TITLE
Add wrapper functions for FCGI_Finish and fflush()

### PR DESCRIPTION
**Pull request by fmqa**
* Add a wrapper for FCGI_Finish to allow the caller to end the current request
* Add a wrapper for fflush() to facilitate streaming responses

### CODE REVIEW

**Comment by mikejsavage** [comment]
Hey thanks for the PR. It's been a while since I worked on this so you probably understand it better than I do at this point

I'm struggling to see what `FCGI_Finish` is useful for. You can kind of abort responses already by not sending anything else, which implies you have some kind of logic to stop working in the middle of the response handler (something like pcall/error), and if you call `FCGI_Finish` you will probably want to stop working anyway so you still have to write that code

Of course I may be missing something here so please point it out if I am!

**Comment by fmqa** [comment]
`FCGI_Finish` is useful if you want to do some other processing without leaving the connection open after sending the response. It also flushes the output buffer as a nice side effect (you can use `flush()` to do this too, but if you're done with the request you may as well just call `finish()`)

**Comment by fmqa** [comment]
To elaborate a bit on the earlier comment, let's assume we have the following `accept()` loop:

```lua
while fcgi.accept() do
    fcgi.print( "Content-Type: text/plain; charset=utf-8\r\n\r\n" )
    fcgi.print(<some response payload>)
    do_other_time_consuming_task()
end
```
In the above case, the flushing of the response buffer and the teardown of the client connection will happen on the next `fcgi.accept()` call, which comes after `do_other_time_consuming_task()`

However, if we rewrite the above loop like this:

```lua
while fcgi.accept() do
    fcgi.print( "Content-Type: text/plain; charset=utf-8\r\n\r\n" )
    fcgi.print(<some response payload>)
    fcgi.finish()
    do_other_time_consuming_task()
end
```

The buffers will be flushed and the response will be finalized when `fcgi.finish()` is called, and we do not have to wait until the next `fcgi.accept()` call to finalize the response. In this case, `do_other_time_consuming_task()` doesn't hold up finishing the response.

**Comment by mikejsavage** [comment]
Makes sense!

I'll merge this and roll a new release in the next few days.

**Comment by mikejsavage** [comment]
whoops

**Pull request merged**
